### ISSUE TITLE
Open Maintenance Tasks

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#399]
### General Maintenance and Modernization
- [x] Support Fluid templates for easy content rendering (especially for metadata)
- [x] #1018
- [x] #1045
- [x] Complete and fix phpDoc (in the given order)
  - [x] #1012 (`@package`, `@subpackage`, `@access`, `@abstract`, `@property`)
  - [x] #1013 (`@access`, `@static`, `@var`)
  - [x] #1014 (`@access`, `@static`, `@param`, `@return`)
  - [x] #1011 (since it only works on class level)
- [ ] #1015 (see [Auto generated structure](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/FilesAndLocations/Index.html#ext-tables-sql))
- [x] #1010

### Update Dependencies
- [x] Clean up and update Javascript libraries
  - [x] jPlayer
  - [x] jQuery
  - [x] jQuery UI
  - [x] OpenLayers
