### ISSUE TITLE
Support for TYPO3 v9.x

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#498]
**Open Tasks:**
- [x] Replace `css_styled_content` by using alternate menu builder, etc.
- [x] Replace old database functions with QueryBuilder API (see [documentation](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Database/Migration/Index.html))
  - [x] Replace `Helper::whereClause()` by `FrontendRestrictionContainer` or `Helper::whereExpression()` if necessary or remove otherwise (see [documentation](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Database/RestrictionBuilder/Index.html))
  - [x] `Classes/Common/IiifManifest.php` (#519)
  - [x] `Classes/Plugin/Basket.php` (#519)
  - [x] `Classes/Plugin/Feeds.php` (#515) 
  - [x] `Classes/Plugin/OaiPmh.php` (#503)
  - [x] Remove method `whereClause()` from `Classes/Common/Helper.php` (#519)
- [x] Remove/update dependencies on `\TYPO3\CMS\Backend\Form\FormEngine`
- [x] Check for deprecated and removed functions and replace them
  - [x] `ExtensionManagementUtility::siteRelPath()` (#509)
  - [x] `\TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::fileResource()`
  - [x] `\TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::getSubpart()` and `\TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::substituteMarkerArray()`
  - [x] Remove parameter `$hsc` from calls to methods `getLL()`, `getLLL()` and `pi_getLL()` and use `htmlspecialchars()` function directly instead (#514)
